ENH: Resize flat correction image by binning for Andor corrections
jrojasUNC/PlusLib pull request #1
Opened 2021-02-12 20:27 UTC by adamaji

@jrojasUNC here are the changes for the single flat image -- do you think we should change the interpolation? Currently it is using INTERP_LINEAR which is the default. The docs say that INTERP_AREA is best for shrinking:

>INTER_AREA - resampling using pixel area relation. It may be a preferred method for image decimation, as it gives moire’-free results. But when the image is zoomed, it is similar to the INTER_NEAREST method.

2021-02-13 13:59 UTC, jrojasUNC commented
I don't think it really matters. The flat Image doesn't change too quickly. I shrunk by a factor of 8 (worst case) and then enlarged by a factor of 8, and divided the result by the original image. with all methods the difference is <3%. Cubic seems to be the best:
![image](https://user-images.githubusercontent.com/20046115/107851648-86b0da00-6dd9-11eb-87bf-d617bdf73990.png)

This was matlab so the results will probably slightly different with OpenCV. I think "box" is similar to INTER_AREA.

2021-02-13 14:19 UTC, jrojasUNC commented
Looking over the logs, I got this error for every acquisition so it was probably not doing flat correction at all. 
`
Server error: |ERROR|608.485000| FlatCorrectionImage size [1024 x 1024] does not the current frame size 128 x 128| in C:\SP\SPF21\PlusLib\src\PlusDataCollection\Andor\vtkPlusAndorVideoSource.cxx(743)`

2021-02-13 14:24 UTC, jrojasUNC commented on src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
> +  cv::resize(cvFlatCorrection, cvResizedFlatCorrection, cvFlatCorrection.size(), 1.0 / binning, 1.0 / binning);
binning needs to be cast to a float. I think what's happening is that 1/binning = 1 so the size stays 1024x1024

2021-02-13 15:19 UTC, jrojasUNC commented
this should change to make sure the flat image is the size of the detector, not the current frame size .
https://github.com/jrojasUNC/PlusLib/blob/ce93857099d44b9fff878b55bde32f42b920b60d/src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx#L976

2021-02-14 22:31 UTC, jrojasUNC commented
For some really annoying reason it's not letting me push but here is what I changed and I'm pretty sure it works:
![image](https://user-images.githubusercontent.com/20046115/107891071-602e9400-6eea-11eb-91cf-67c1d00b875a.png)

2021-02-15 15:06 UTC, adamaji commented
I think this is fine, especially if the data looks fine in the lab. Only thing about the cubic interpolation is perhaps that it's potentially slower, not sure by how much

2021-02-15 16:23 UTC, dzenanz requested changes

2021-02-15 16:23 UTC, dzenanz commented on src/PlusDataCollection/Andor/vtkPlusAndorVideoSource.cxx
> +  cv::resize(cvFlatCorrection, cvResizedFlatCorrection, cvFlatCorrection.size(), 1.0 / binning, 1.0 / binning);
Resizing the correction image in each frame is not necessary. Perhaps have an `std::map<int, cv::Mat>` where we keep the cached versions of `cvResizedFlatCorrection`. Of course, clear it when a new flat correction image is set. We could also apply the same approach to the other correction images too. This way, we could use high-quality cubic resizing, as we would be doing it only once.

2021-02-16 15:20 UTC, jrojasUNC commented
@dzenanz @adamaji I merged changes into my original branch so the changes can be seen there now https://github.com/jrojasUNC/PlusLib/commits/remove-background-from-cosmic-correction. Dzenan, I copied what you did for the  bad pixel correction so not it doesn't resize every time.

2021-02-16 15:23 UTC, dzenanz commented
Looks good now.

2021-02-16 18:10 UTC, adamaji commented
Closing this as the changes have made it into PlusLib via a different branch

2021-02-16 18:10 UTC, closed without merging